### ISSUE TITLE
Ready for Pilot Workshops?

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/high-dimensional-stats-r#1]
Hi @Alanocallaghan and Gail Roberston!

I'm working on organizing a series of mini-workshops for next semester at my institution.  We are hoping to pilot some of incubator lessons.  We have an instructor interested in teaching this lesson.  Do you think this lesson would be in a good place to pilot later this year?  Any additional info you could share in it?  We could also provide feedback from learners/instructors/helpers.

Happy to meet and discuss more. If you'd like to set up a meeting, let me know.

Best,
Sarah

cc: @SteveGoldstein

**Comment by Alanocallaghan** [comment]
Hi Sarah.

This lesson will likely be ready for piloting in full around September-October this year. The intention is that it'll be roughly a 2-day workshop, the first run of which is scheduled for October. I'd be very keen for more pilot workshops of course.

There are some other lessons that likely fit fairly well with it, eg https://github.com/carpentries-incubator/statistical-thinking-public-health and a python course on machine learning for public health that I believe is not in the incubator atm

Any other questions let me know

cc @ailithewing

**Comment by catavallejos** [comment]
Hi @sstevens2,

Are you still interested in piloting this workshop? We have now run 2 full sessions of it. We plan to make some edits to the materials, but a lot of the content is more mature now. Happy to keep you on the loop if that's helpful.

Best

Cata

**Comment by sstevens2** [comment]
Hi @catavallejos,

Thanks for getting back to me.  We have a number of other pilots planned for the upcoming months so it is unlikely we will try to pilot this one soon.  I'll close this issue and reach back out if we do.

Thanks!
