### ISSUE TITLE
minfi error when building the website

### ISSUE THREAD

**Issue by catavallejos** [carpentries-incubator/high-dimensional-stats-r#103]
After merging the last set of changes, I get an error because `minfi` cannot be installed. 

As far as I understand, `minfi` is not needed as we have a 'local' copy of the methylation data. @hannesbecher could you please check this? I am not quite sure why we are loading `minfi` in all/some episodes. 

If we remove it we will also need to update https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/main/dependencies.csv accordingly and add a note to say what's the source of the data (similar to what was done for the prostate dataset)

Thanks!

**Comment by alanocallaghan** [comment]
I can fix this today

**Comment by alanocallaghan** [comment]
Sorry for the delay, I try to monitor the build system but do feel free to ping me if it breaks again
