### ISSUE TITLE
Review comments: Episode 2 - regression with many outcomes 

### ISSUE THREAD

**Issue by mallewellyn** [carpentries-incubator/high-dimensional-stats-r#114]
[Episode 2](https://carpentries-incubator.github.io/high-dimensional-stats-r/02-high-dimensional-regression/index.html)

Again, I really like this episode and believe it's really valuable to explore many outcomes as well as many predictors! I have a few comments here again. This time the comments are largely "queries" about the content. 

I will again submit pull requests where possible :)

- Line 61/DNA methylation data: Query - I'm not sure what this object is - is it derived from an object, which in turn is derived from a class? And what does this mean? This possibly makes more sense to someone familiar with Python rather than R. I'm really not sure without understanding, but perhaps there's a way to simplify the language/remove anything not relevant to the subsequent analysis and reference the vignette as you have done?

- Line 75/DNA methylation data: Initially reading this I thought we had many more observations that features. I think putting the statement that "samples or observations are stored as columns, while features (in this case, sites in the genome) are stored as rows" first would help clarify. The first sentence stating the number of features etc could come after this. Also, stating number of rows/columns and then stating the translations to features and "observations/samples" in this sentence could help clarify. 

- Line 110/DNA methylation data: Query - is this definitely the Prostate data or is this a typo (should it be the methylation data)?

- Line 112/Figure caption: Query - it's unclear to me in what way there are too many models to fit by hand. And if you mean by hand or using R but using a model formula? The examples below are just two models, right? And we could fit these in R pretty easily (they just might not be very good? Is this clarified by "it's clear that there's too many features to fit each possible model (combination of features) separately"

But if this latter statement is correct, how does this link to points (1) and (2) that follow?

- Line 129/DNA methylation data: Perhaps something like "In general, it is scientifically interesting to answer two main questions using the three types of data:"

- Line 145/Challenge 1: Query - possibly quote the name of the column rather than "columns in colData" to clarify what relationship we're hypothesising? How does this relate to the age-related problems above? Have I misunderstood?

- Line 206/Regression with many outcomes: Query - the first two paragraphs of this section make perfect sense to me, but it's unclear to me how the plots relate to the third paragraph and regression with many outcomes overall and then how looking at linear regression helps.

_Minor comments:_ 

- Line 11/Objectives: "high dimensional regression" -> "high-dimensional regression"

- Line 64/DNA methylation data: ", and optional sample-level colData and feature-level metadata" should this be ", optional sample-level colData, and feature-level metadata"?

- Line 140/DNA methylation data: Possibly clearer to swap the order in the list above and say we focus on the first problem here and second problem next?

- Line 132/DNA methylation data: "leves" -> "levels"

- Line 157/Challenge 1: "signif" -> significant

- Line 224 & 228/Regression with many outcomes: "primary" -> "first", "secondary" -> "second"?

- Line 229/Regression with many outcomes: "in very high-dimensional..." -> "when implemented on very high-dimensional..."

- Alt text and captions for figures.

This could well be me misunderstanding things, please feel free to correct me!

**Comment by alanocallaghan** [comment]
Reading over your comments regarding motivation, particularly

> Line 112/Figure caption: Query - it's unclear to me in what way there are too many models to fit by hand. And if you mean by hand or using R but using a model formula? The examples below are just two models, right? And we could fit these in R pretty easily (they just might not be very good? Is this clarified by "it's clear that there's too many features to fit each possible model (combination of features) separately"

makes me think that I probably didn't do a very good job of framing this as both a problem (many related models) and a bonus/opportunity (sharing information across related features)

**Comment by mallewellyn** [comment]
Convert to task list. Ordered by line number rather than major/minor to avoid merge conflicts.

- [ ] 1. Line 11: "high dimensional regression" -> "high-dimensional regression"

- [ ] 2. Line 61: clarify object or possibly remove if not essential to the subsequent analysis

> Query - I'm not sure what this object is - is it derived from an object, which in turn is derived from a class? And what does this mean? This possibly makes more sense to someone familiar with Python rather than R. I'm really not sure without understanding, but perhaps there's a way to simplify the language/remove anything not relevant to the subsequent analysis and reference the vignette as you have done?

- [ ] 3. Line 64: ", and optional sample-level colData and feature-level metadata" -> ", optional sample-level colData, and feature-level metadata"?

- [ ] 4. Line 75: add clarification of observations/features.

> Initially reading this I thought we had many more observations that features. I think putting the statement that "samples or observations are stored as columns, while features (in this case, sites in the genome) are stored as rows" first would help clarify. The first sentence stating the number of features etc could come after this. Also, stating number of rows/columns and then stating the translations to features and "observations/samples" in this sentence could help clarify.

- [ ] 5. Line 110: possibly methylation data?

> Query - is this definitely the Prostate data or is this a typo (should it be the methylation data)?

- [ ] 6. Line 112: frame as problem and bonus opportunity 
- [ ] 7. Line 112: link to points (1) and (2)

> Query - it's unclear to me in what way there are too many models to fit by hand. And if you mean by hand or using R but using a model formula? The examples below are just two models, right? And we could fit these in R pretty easily (they just might not be very good? Is this clarified by "it's clear that there's too many features to fit each possible model (combination of features) separately"

> But if this latter statement is correct, how does this link to points (1) and (2) that follow?

- [ ] 8. Line 129: Perhaps something like "In general, it is scientifically interesting to answer two main questions using the three types of data:"

- [ ] 9. Line 132: "leves" -> "levels"

- [ ] 10. Line 140: Possibly clearer to swap the order in the list above and say we focus on the first problem here and second problem next?

- [ ] 11. Line 145: add clarification of the relationship we're hypothesising and how this relates to the age-related model.

> Query - possibly quote the name of the column rather than "columns in colData" to clarify what relationship we're hypothesising? How does this relate to the age-related problems above? Have I misunderstood?

- [ ] 12. Line 157: "signif" -> "significant"

- [ ] 13. Line 206: clarify how plots relate to the third paragraph and regression with many outcomes overall, and how looking at linear regression helps.

> Query - the first two paragraphs of this section make perfect sense to me, but it's unclear to me how the plots relate to the third paragraph and regression with many outcomes overall and then how looking at linear regression helps.

- [ ] 14. Line 224 & 228: "primary" -> "first", "secondary" -> "second"?

- [ ] 15. Line 229: "in very high-dimensional..." -> "when implemented on very high-dimensional..." 

- [ ] 16. Figure captions.

**Comment by alanocallaghan** [comment]
https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/57f2f5b2d6dbb9c8f190542e34da2ba0979acd73/_episodes_rmd/02-high-dimensional-regression.Rmd#L515-L516

"the the"

**Comment by mallewellyn** [comment]
- [ ] Line 515: "the" twice

**Comment by alanocallaghan** [comment]
https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/57f2f5b2d6dbb9c8f190542e34da2ba0979acd73/_episodes_rmd/02-high-dimensional-regression.Rmd#L703

- [ ] "Points higher on the x-axis" -> "Points higher on the y-axis"

**Comment by mallewellyn** [comment]
In line 58, is "Note: the code that we used to download these data from its source is available
[here](https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/main/data/methylation.R)" needed?

**Comment by alanocallaghan** [comment]
> In line 58, is "Note: the code that we used to download these data from its source is available
[here](https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/main/data/methylation.R)" needed?

The intention was just to point people to the pre-processing code, as this is generally advised in carpentries lessons, but maybe it's better to just have an overall "data" page we can point to

**Comment by mallewellyn** [comment]
I see. Perhaps best left for now and can point to a data page once it's been created?

**Comment by alanocallaghan** [comment]
https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/57f2f5b2d6dbb9c8f190542e34da2ba0979acd73/_episodes_rmd/02-high-dimensional-regression.Rmd#L919-L921

- [ ] Seed should be set when scrambling data

**Comment by alanocallaghan** [comment]
https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/57f2f5b2d6dbb9c8f190542e34da2ba0979acd73/_episodes_rmd/02-high-dimensional-regression.Rmd#L946-L948

imo "Under the null hypothesis" here is confusing phrasing. To be discussed, though

https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/57f2f5b2d6dbb9c8f190542e34da2ba0979acd73/_episodes_rmd/02-high-dimensional-regression.Rmd#L1072-L1074

- [ ] FDR has to be specified to answer this

**Comment by mallewellyn** [comment]
Re task 11, I just want to clarify before making any changes. Is challenge 1 asking why we can't just formulate a model to predict methylation values by

1) regressing each feature of the methylation M-value matrix on age in individual models
2) choose all models with a significant age coefficient
3) combine these models in some way to formulate an overall model to predict methylation levels?

Not sure how 3) would work so I think I've definitely misunderstood. 

Point of confusion is likely linked to the point the episode is refined to addressing by the text immediately above:
"Predicting methylation levels using age as a predictor. In this case, we would have 5000 outcomes (methylation levels across the genome) and a single covariate (age)."

**Comment by alanocallaghan** [comment]
The first challenge is meant to get people to think about:

> Why is blindly fishing for associations between (eg) DNA methylation and all available covariates not the best idea?

ie, why not just regress age against every methylation locus, then regress smoking status against every methylation locus, also regress batch against locus, etc, etc, and build some post-hoc rationalisation out of the significant results we observe? What is wrong with data dredging, etc.

The intention isn't really to consider combining features, just to get people to think about data dredging, experimental design, model validity, etc

**Comment by mallewellyn** [comment]
Ah I think I understand. I think the points (1) and (2) above confused me. I'll propose putting this challenge before the high-dimensional problems relating specific variables but happy to discuss

**Comment by alanocallaghan** [comment]
Well, if you're confused, it's likely learners will be, so happy to see things rearranged.

I also proposed re-ordering the solutions in #128, which I think makes much more sense (and, it fixes the markdown list formatting)

**Comment by mallewellyn** [comment]
Ah great ok. I've made some edits that are hopefully complementary

**Comment by mallewellyn** [comment]
All addressed in merged pull requests
