### ISSUE TITLE
Merging and updating build ahead of workshops

### ISSUE THREAD

**Issue by mallewellyn** [carpentries-incubator/high-dimensional-stats-r#116]
Would it be possible to merge the approved pull requests and rebuild the website before the next teaching round begins (27th February). 

Happy to give the website build a go if this helps.

**Comment by alanocallaghan** [comment]
Hmm, yeah build works, but isn't updating. https://github.com/carpentries-incubator/high-dimensional-stats-r/commit/41d4874b1744a89bad6573919cadb9410a4dea6d

**Comment by alanocallaghan** [comment]
I don't think I'll be able to fix the auto-builds before the next batch of lessons, so will probs just build things locally and push, so poke me if anything needs updating basically. Have done these updates at least...

**Comment by mallewellyn** [comment]
Thanks so much for building things locally to fix this. I won't have any further pre-lesson updates but will see if the teaching team has spotted anything.
