### ISSUE TITLE
Further pre-workshop update to dependencies 

### ISSUE THREAD

**Issue by mallewellyn** [carpentries-incubator/high-dimensional-stats-r#122]
Hi, 
The dependencies.csv file referenced in the setup tries to retrieve from an empty file in the gh-pages branch, giving errors when running

download.file(
    "https://raw.githubusercontent.com/carpentries-incubator/high-dimensional-stats-r/gh-pages/dependencies.csv",
    destfile = 'dependencies.csv'
)

Changing the url to the main branch works: 

 download.file(
    "https://raw.githubusercontent.com/carpentries-incubator/high-dimensional-stats-r/main/dependencies.csv",
    destfile = 'dependencies.csv'
)

The second link in the setup can also be changed to reference the main branch without any issues as far as I'm aware. 

Alternatively, as a short term fix, could add fill the dependencies.csv on the gh-pages branch!

For some reason I can't edit the setup.md file in the main branch or I'd submit a pull request for this!

**Comment by alanocallaghan** [comment]
Ah, seems like the calls to `renv::dependencies()` were always wrong (should be `errors="ignored"` not `error="ignore"`, but previously this was fine with partial matching. Broke at some point. Evidently I pushed an empty file the other day because of this.

Should be fixed now.
