### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by alanocallaghan** [carpentries-incubator/high-dimensional-stats-r#33]
Day 1 Feedback:
positives:
- I liked that it was a very practical example
- Examples are very clear and easy to understand as a biologist  
- Easy to follow
- Good stepwise explanations when live coding
- I liked the pace and depth of explanations of each topic

suggestions for improvement:
- Some of the equations are written out in code but not visible as equations in the html page (displays fine for me on firefox but not on chrome-based browsers)
- At times pace could be a bit faster
- Perhaps dwelling on simpler and widely understood concepts (e.g. Bonferroni correction) unnecessary
- Feel like we could go through the material a bit quicker and and just summerise some coding answers instead of live coding them again.
- feel like we could go through the exercises a bit quicker

Day 2:
Positives:
- informative figures in the slides and I liked how Alan went through the plots step by step
    
Suggestions for improvement:
- It was quite theoretical and I missed some examples of practical application

Day 3:
Positives:
- The step by step walking through how the R objects looked like was helpful in thinking about how to plot / analyse the data!
Suggestions for improvement:
- it would be great to have the codes available maybe with some comments explaining what the code does. I can follow today but if i look at it in a month i think i won't remember what i've done and I am trying to cope with the speed of coding and  catching up as well. Overall its a really useful course!
- The theoretical explaination in the slides went a little too quick for me!

Day 4:

Positives:
- It was good to evaluate the hierarchical clustering with lots of plots. The visulasiation makes it easier to conceptualise.

Suggestions for improvement:
- It could be better if we have more examples of a method. In different cases, the use of the method may be different.
- I would've liked an overview of the general steps for each method, just to recap what the specific characteristics of the methods are and when they're useful.

**Comment by Alanocallaghan** [comment]
Feedback from me:

the introduction can be shortened and made more specific. Focus on showing the difficulties of high-d data, and not showing things that are done in other episodes.

Ep2 should have been taught quicker with more detail on other correction methods (#45).

ep3 should maybe be a bit more practical and explain why these methods are good vs bad (eg, lots of features with small contributions vs subset selection which is better in converse case). Try find some pathological case. Emphasise sample size for CV.

Factor analysis should maybe be a bit more detailed and I think not subsetting the data may make more sense.

PCA was v good, maybe should annotate the genes and add a callout on identifying what's going on in a PC

k-means seems fairly good but need to tie back to PCA a bit more re: elbow point etc

hcluster is good but I think introducing it by clustering feature-feature correlation and then going back to clustering observations is confusing

**Comment by hannesbecher** [comment]
* Ep 1 shortened
* FA overhauled
* many other parts adjusted/reordered according to comments/requests
