### ISSUE TITLE
review comments: setup.md

### ISSUE THREAD

**Issue by 3mmaRand** [carpentries-incubator/high-dimensional-stats-r#34]
destfile argument is missing from download.file() command
e.g  destfile = "dependencies.csv"

Maybe add a few comments to the set up and give an indication of time taken?

For ref: I did in a fresh RStudio Cloud Project (public: https://rstudio.cloud/project/3121818),  attempted package installation of all 50 packages took 30 mins and I had several fails:
1: package(s) not installed when version(s) same as current; use `force = TRUE` to re-install: 'stats' 'MASS' 'cluster' 'BiocManager' 'utils' 
2: In .inet_warning(msg) :
  installation of package ‘scran’ had non-zero exit status
3: In .inet_warning(msg) :
  installation of package ‘GenomicFeatures’ had non-zero exit status
4: In .inet_warning(msg) :
  installation of package ‘bumphunter’ had non-zero exit status
5: In .inet_warning(msg) :
  installation of package ‘ensembldb’ had non-zero exit status
6: In .inet_warning(msg) :
  installation of package ‘minfi’ had non-zero exit status
7: In .inet_warning(msg) :
  installation of package ‘scRNAseq’ had non-zero exit status
8: In .inet_warning(msg) :
  installation of package ‘IlluminaHumanMethylationEPICanno.ilm10b4.hg19’ had non-zero exit status
9: In .inet_warning(msg) :
  installation of package ‘IlluminaHumanMethylationEPICmanifest’ had non-zero exit status
10: In .inet_warning(msg) :
  installation of package ‘FlowSorted.Blood.EPIC’ had non-zero exit status

**Comment by catavallejos** [comment]
Thanks @3mmaRand for the feedback. Here is what we plan to do:

1) Edit setup.md with an expectation of how long setup takes. 
2) Check whether dependency list can be made shorter. 
3) Check setup runs smoothly in different environments.

We will also explore whether to provide a Docker container with all the requirements for the course.

I will close this issue for now as I have moved these to our master to-do list in #64 

Of course, just re-open this issue if you have further comments.
