### ISSUE TITLE
Remove or explain more of the linkage methods

### ISSUE THREAD

**Issue by alanocallaghan** [carpentries-incubator/high-dimensional-stats-r#40]
The methods that produce weird dendrograms are probably useful for some scenarios so just showing them failing here is maybe underselling them. Prob best to recommend settings imo

**Comment by catavallejos** [comment]
Does this refer to a specific episode?

**Comment by Alanocallaghan** [comment]
eg challenge 3 here used to go through all the linkage methods (some of which people will probably never use) without explaining any: https://carpentries-incubator.github.io/high-dimensional-stats-r/07-hierarchical/index.html

I think it would be better to give a concrete explanation of the most common methods used in biology (complete and ward/ward.d2), then say "There are also other linkage methods available, which are described in more detail [somewhere else]".

Presenting a bunch of different dendrograms without explaining why they're different and which may be "better" raises more questions than it answers and is just likely to leave people feeling confused, imo

**Comment by hannesbecher** [comment]
Working on it. It is essentially about adding material that helps to visualise the effect of different distance and linkage methods.

Planning to simulate some data for this.
