### ISSUE TITLE
Convert slides from pdf to Rmd/html

### ISSUE THREAD

**Issue by Alanocallaghan** [carpentries-incubator/high-dimensional-stats-r#43]
This means they can be updated/re-ordered easily (also switched back to pdf if needed)

**Comment by catavallejos** [comment]
Not sure this is longer needed. I didn't use the slides when I taught the course. @hannesbecher do you know if the slides were used by other instructors?

**Comment by Alanocallaghan** [comment]
I think if people use slides/notes it's better to just make some custom ones rather than my engineered solution anyways. Was foiled by some limitations in knitr anyways.
