### ISSUE TITLE
Explain Bonferroni/FDR a bit less, add qvalue back to ep2

### ISSUE THREAD

**Issue by Alanocallaghan** [carpentries-incubator/high-dimensional-stats-r#45]
Prob a lot of people will know one or both, so good to at least introduce the idea of adaptive FDR

**Comment by catavallejos** [comment]
I am inclined to leave as is, but could re-consider if there are strong feelings about it.

**Comment by Alanocallaghan** [comment]
That's fine, was based on some initial feedback about spending a decent amount of time on FDR/FWER methods that people understood. However I think that cohort may have been skewed a bit as there were a couple of maths folks in it

Would be a decent idea to add a callout box (ie something to discuss if people are interested, but not required), but I'm unlikely to do that unless I get *really* bored

**Comment by catavallejos** [comment]
oh - I am sure you will have plenty of other things to keep you busy in boring times :-)
