### ISSUE TITLE
Actions problems

### ISSUE THREAD

**Issue by Alanocallaghan** [carpentries-incubator/high-dimensional-stats-r#51]
Recent build actions are skipped, eg https://github.com/carpentries-incubator/high-dimensional-stats-r/actions/runs/1842306596 or https://github.com/carpentries-incubator/high-dimensional-stats-r/actions/runs/1842192882

The latter provides the error `An error occurred while provisioning resources (Error Type: Failure).`

Seems maybe this is either a random thing or a resource usage thing https://github.community/t/jobs-on-macos-latest-sometimes-gets-cancelled-an-error-occurred-while-provisioning-resource/17434/13

**Comment by catavallejos** [comment]
Hi @Alanocallaghan this seems to be resolved no?

**Comment by Alanocallaghan** [comment]
I guess so yeah
