### ISSUE TITLE
Factor Analysis conceptual suggestions

### ISSUE THREAD

**Issue by christiebarron** [carpentries-incubator/high-dimensional-stats-r#53]
Hi there! 

I'm new to Carpentries and quite a weak coder. But I do have extensive experience with factor analysis within a social studies context and have a few suggestions about conceptual ideas if they're relevant. I totally understand things must be kept brief due to time contraints, but I think there are a few concepts that can be helpful.

EFA vs CFA: I wonder if it may be useful to describe the differences between exploratory and confirmatory factor analysis. As far as I can see, your analyses seem to be exclusively using EFA. Even if just focusing on EFA, it may be useful to mention there are more confirmatory approaches too. As of now, students may assume that EFA is the only method of factor analysis available.

Factor Enumeration: I wonder if it may be useful to briefly mention that there are various methods for determining the optimum number of latent factors in EFA. You don't even have to mention Kaiser's criterion, Cattel's scree plots,  Horn's parallel analysis, and Velicer's minimal average partial, but just mentioning there being methods available may be helpful. 

Next steps: I think pointing students towards R packages that make factor analysis easier may be beneficial. the psych package (running EFA), EFA.dimensions package (factor enumeration for EFA), and lavaan (CFA) are also incredibly useful. 

I am happy to discuss or try to implement any of the comments raised further!

Many thanks,
Christie

**Comment by Alanocallaghan** [comment]
Super helpful comments, thanks!

**Comment by hannesbecher** [comment]
Hi @christiebarron ,
We have now updated the FA episode to include EFA and CFA. Also added links to packages at the end.

If you happen to have the time, would you mind taking a look, please? Any suggestions welcome!

https://carpentries-incubator.github.io/high-dimensional-stats-r/05-factor-analysis/index.html

**Comment by christiebarron** [comment]
Hello Hannes,

Sorry for the late reply.

That looks great!! A couple quick suggestions are provided in the table
below. It looks great even without any changes. Feel free to
incorporate/exclude my changes as you see fit.

Cheers,
Christie

**Comment by hannesbecher** [comment]
Thank you @christiebarron for going through the episode! I am not sure I can see the table you mentioned 😀

**Comment by christiebarron** [comment]
Ahh, apologies. I replied through my email and sent a word doc attachment that didn't seem to go through. The table can be accessed here: https://docs.google.com/document/d/1saauQAw0-Wm0CLaH9yAzprBKmR7n5Zigufs6Asn7hMs/edit?usp=sharing

[suggested revisions.docx](https://github.com/carpentries-incubator/high-dimensional-stats-r/files/10717588/suggested.revisions.docx)

**Comment by hannesbecher** [comment]
Thanks very much again!
I've implemented you suggestions.
