### ISSUE TITLE
08-k-means.Rmd depends on orphaned package (cairoDevice)

### ISSUE THREAD

**Issue by nathansam** [carpentries-incubator/high-dimensional-stats-r#55]
At the moment, it is impossible to build the entire site. 08-k-means.Rmd depends on `{cairoDevice}`, however this package was [orphaned by CRAN last December](https://cran.r-project.org/web/packages/cairoDevice/index.html)  https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/7ff074f03a9133b7c020ac0923e58f01de5e0f83/_episodes_rmd/08-k-means.Rmd#L318

**Comment by Alanocallaghan** [comment]
Should work now, lmk if not obviously

**Comment by nathansam** [comment]
All working now! Ty
