### ISSUE TITLE
Potential changes to optional episodes 

### ISSUE THREAD

**Issue by catavallejos** [carpentries-incubator/high-dimensional-stats-r#65]
- 03 (from #7):
  - [ ] machine learning course isn't carpentries and should be linked (or an alternative 
  - [ ] forward stepwise description a bit sparse
  - [ ] forward/reverse could do with more detail

- 10 (from #7):
  - [x] explain densfun warnings (good Q)
  - [x] error in dnorm, exercise 1
  - [x] warnings in histograms (suppress?)
  - [x] #17
  - [ ] more detail on fitting a bivariate normal

**Comment by mallewellyn** [comment]
Are all of the tasks above resolved now that the [optional episode](https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/bfb3af3b1a23780704a39bcac62611cd153b3040/_episodes_rmd/04-regression-feature-selection.Rmd) has been removed?

**Comment by alanocallaghan** [comment]
Yes
