### ISSUE TITLE
Self-review notes

### ISSUE THREAD

**Issue by Alanocallaghan** [carpentries-incubator/high-dimensional-stats-r#7]
Some notes for revisions after largely finishing content.

In general:
- revise timings
- revise/clarify questions/objectives/keypoints
- probably don't title sections boringly like "introduction"
- more "further reading" links

- 02:
  - [x] description of linear regression could use more detail
  - [x] screening should use permuted age
  - [x] plot labels/legends are at times iffy

- 03:
  ~- [ ] plot labels~ **moved to #64**
  - [x] callout box on collinearity
  - [x] brackets on yhat - y -> fixed by 7ff074f03a9133b7c020ac0923e58f01de5e0f83
  ~- [ ] 2nd exercise a bit on-the nose~ **agreed to skip (see comments below)**
  ~- [ ] maybe ask why mean squared rather than sum of squared~ **moved to #64**
  ~- [ ] brackets on l2 norm/ridge equation a bit confusing~ **moved to #64**
  ~- [ ] phrasing convoluted in "why would we...?"~ **moved to #64**
  ~- [ ] callout box on flipping signs~ **I don't think this is needed, trying to restrict too many extra info**
  ~- [ ] bayesian callout box needs finishing~ **Ailith and I decided to leave Bayesian refs out as there is no time to cover background knowledge**
  ~- [ ] lasso bayesian callout box~ **Ailith and I decided to leave Bayesian refs out as there is no time to cover background knowledge**
  - [x] finish bias-variance callout, make it distinct from elastic net. should come before final exercise
  - [x] explain multinomial warnings in text

~- 04:~ **moved to #65**
  ~- [ ] machine learning course isn't carpentries and should be linked (or an alternative~ 
  ~- [ ] forward stepwise description a bit sparse~
  ~- [ ] forward/reverse could do with more detail~
 
~- 09: Moved to #64~
  ~- [ ] exercise 1 bugged~
  ~- [ ] initial mcq before callout?~
  ~- [ ] title for 1st practical bit~
  ~- [ ] formal description of silhouette width~
  ~- [ ] k of 5 or k=5, not both~
  ~- [ ] title for introducing bootstrap~
  ~- [ ] title for applying bootstrap~
  ~- [ ] more detail on bootstrap~

~- 10:~ **moved to #65**
  ~- [ ] explain densfun warnings (good Q)~
  ~- [ ] error in dnorm, exercise 1~
  ~- [ ] warnings in histograms (suppress?)~
  ~- [x] #17~
  ~- [ ] more detail on fitting a bivariate normal~

**Comment by catavallejos** [comment]
@Alanocallaghan in the list above, 03 and 04 are in the reverse order no?

**Comment by catavallejos** [comment]
@Alanocallaghan for 03 you wrote: *2nd exercise a bit on-the nose* ... unless you have specific comments, I will skip

**Comment by Alanocallaghan** [comment]
I think that's referring to the fact that it's asking students exactly what they've just been told for q1, and q2 essentially recaps the normality of residuals assumption, which on reflection we shouldn't really emphasise given it's not super important. Can be ignored for now
