### ISSUE TITLE
Leftover issues in Intro episode

### ISSUE THREAD

**Issue by catavallejos** [carpentries-incubator/high-dimensional-stats-r#74]
After compiling the website, I could find some unresolved issues:

- [ ] In Challenge 1, the answer for 4. is missing. 
- [ ] In the solution to Challenge 2, the requested changes failed to propagate 
- [ ] Same for Challenge 3. 

@hannesbecher can you go through and see if I missed anything. 

Note: I think this happened whenever my review was indicated as comments rather than direct suggested edits.

**Comment by hannesbecher** [comment]
I think this is OK now.
