### ISSUE TITLE
Addition to Extra Resources

### ISSUE THREAD

**Issue by Harithaa-Anandakumar** [carpentries-incubator/high-dimensional-stats-r#76]
I think adding a few non-book/text based resources within the  "Extra resources" field could also be useful. 

For instance, the youtube channel `StatQuest`  by `Josh Starmer` has some wonderful fundamental videos on high dimensional stats and off-late ML as well. (https://www.youtube.com/c/joshstarmer). This has personally been really helpful for me in nailing the fundamentals. 

These are my two cents, 
Harithaa

**Comment by catavallejos** [comment]
Thanks @Harithaa-Anandakumar. We will consider this in our next round of edits.

**Comment by catavallejos** [comment]
Now added to the introduction episode. Thanks again @Harithaa-Anandakumar !
