### ISSUE TITLE
Renamed files are not removed from gh-pages branch on website build

### ISSUE THREAD

**Issue by Alanocallaghan** [carpentries-incubator/high-dimensional-stats-r#79]
See discussion in #77

**Comment by tobyhodges** [comment]
I remember running into this myself in the past, and indeed an issue was opened in Feb last year to report it: https://github.com/carpentries/styles/issues/544 Looks like @zkamvar made a fix in https://github.com/carpentries/styles/pull/545 - might this work for you here as well?

**Comment by catavallejos** [comment]
Thanks for the suggestion. I edited our website.ylm to see if this helps
