### ISSUE TITLE
GH actions takes far too long

### ISSUE THREAD

**Issue by Alanocallaghan** [carpentries-incubator/high-dimensional-stats-r#81]
There's most likely a way to make the build process much faster.

My suggestions:

- docker image
- better R package caching (maybe borrow an action or two from repos that do it well)
- Reduce number of dependencies, and/or try to prevent scripts being needlessly triggered

**Comment by catavallejos** [comment]
Good ideas ! I will try to explore during the next round of edits.

**Comment by catavallejos** [comment]
Should we close this now @Alanocallaghan ?

**Comment by Alanocallaghan** [comment]
Yeah, down from ~1hr to like ~10mins is fine. May break occasionally if the docker image gets out of date; I'll try to automate that build also.

**Comment by catavallejos** [comment]
Thanks @Alanocallaghan !

**Comment by catavallejos** [comment]
PS: and sorry for all the spam today, just trying to close as many issues as we can before going through formal peer-review

**Comment by Alanocallaghan** [comment]
All good, I should really do issue cleanup more often anyways

**Comment by catavallejos** [comment]
Don’t do them often either, but feels good 😊

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
