### ISSUE TITLE
Explain design / model matrix more?

### ISSUE THREAD

**Issue by ewallace** [carpentries-incubator/high-dimensional-stats-r#86]
Currently the lesson refers to design / model matrices several times starting in episode 2 with:

> The process of running a model in limma is somewhat different to what you may have seen when running linear models. Here, we define a model matrix or design matrix, which is a way of representing the coefficients that should be fit in each linear model. These are used in similar ways in many different modelling libraries.

In instructor discussions on 2022-09-28 delivery with @hannesbecher and @luciewoellenstein44, we are wondering if it would help to explain more. The model/design matrix is a core concept for the lesson, and learners who have only used lm/glm may never have learned it before.

Maybe add a drop-down box explainer in more detail and links to some further reading?

**Comment by Alanocallaghan** [comment]
It would also probably be good to introduce the concept of contrasts in a callout block later in the episode. We don't need them for the model used in that lesson but it'd be good to have content there in case people ask about other experimental designs.

**Comment by catavallejos** [comment]
Model matrix issue addressed by https://github.com/carpentries-incubator/high-dimensional-stats-r/pull/99/commits/29858290fad4f5328dfd71681236c99d5e9da983 

This added a callout box explaining the concept. 

@hannesbecher and I decided to leave the contrasts out, but we could add a link to further reading if needed.
