### ISSUE TITLE
Unresolved FIXMEs

### ISSUE THREAD

**Issue by alanocallaghan** [carpentries-incubator/high-dimensional-stats-r#89]
- https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/b34a6d910d1b7cd50721b6a127682f14ef33b0f2/_extras/discuss.md
- https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/b34a6d910d1b7cd50721b6a127682f14ef33b0f2/reference.md
- https://github.com/carpentries-incubator/high-dimensional-stats-r/blob/b34a6d910d1b7cd50721b6a127682f14ef33b0f2/_extras/guide.md

**Comment by hannesbecher** [comment]
@alanocallaghan  Do we need to fill in these pages?

**Comment by alanocallaghan** [comment]
I'd say we need to fill them out, add a message saying "coming soon", or remove them. I think at the moment they'll be on the live site, including `FIXME`.

**Comment by alanocallaghan** [comment]
Yes, except the glossary. Should we fill this out, or remove it, do you think? I'd be inclined to remove it, but I don't know if that's laziness on my part. It just seems like it'll be duplicating lesson content in a worse form,

**Comment by mallewellyn** [comment]
I think there's a good argument for just including the key points as is - ensuring consistency with the episodes. I'd be inclined to remove it!
